import { writeFileSync, mkdirSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const root = join(__dirname, '..')

const out = join(root, 'src/theme/tokens.css')
mkdirSync(dirname(out), { recursive: true })

// Theme values from Kotlin (verified in Phase 0)
const themes = {
  BLUE: { primary: '#4B559C', bg: '#F0F4F8', card: '#D4E6FF' },
  GREEN: { primary: '#2E7D32', bg: '#E8F5E9', card: '#C8E6C9' },
  PINK: { primary: '#D81B60', bg: '#FCE4EC', card: '#F8BBD0' },
  BROWN: { primary: '#5D4037', bg: '#EFEBE9', card: '#D7CCC8' },
}

// sp → rem: sp / 16
// dp → px: 1:1

const css = `/* Generated by scripts/tokens.ts — do not edit */
:root {
  /* Accent (footnotes, note IDs, delete) */
  --color-accent: #D81B60;
  /* Card body + top bar */
  --color-white: #FFFFFF;
  /* Text */
  --color-text-arabic: #222222;
  --color-text-body: #333333;
  /* Material3 AlertDialog defaults. No MaterialTheme{} wraps the app, so the
     Compose library defaults apply: onSurfaceVariant, and Color.Gray. */
  --color-dialog-text: #49454F;
  --color-dialog-muted: #888888;

  /* Top bar shadow (4 dp = 4px) */
  --shadow-topbar: 0 4px 4px rgba(0,0,0,0.12);
  /* Surah/Ayat chip elevation. Two layers: an offset-0 ambient ring so the
     shade reads on all four sides, plus a small downward drop so the chip
     still looks raised rather than glowing. */
  --shadow-chip: 0 0 2px rgba(0,0,0,0.10), 0 1px 4px rgba(0,0,0,0.16);

  /* Font families (single global place) */
  --font-arabic: 'Noto Naskh Arabic', serif;
  --font-ui: 'Noto Sans Myanmar', sans-serif;

  /* Font sizes (sp ÷ 16 → rem) */
  --fs-arabic: 1.75rem;        /* 28sp */
  --fs-body: 1.125rem;         /* 18sp */
  --fs-arabic-title: 1.375rem; /* 22sp */
  --fs-topbar-en: 1rem;        /* 16sp */
  --fs-topbar-mm: 0.875rem;    /* 14sp */
  --fs-chip: 0.75rem;          /* 12sp */
  --fs-dialog-title: 1.5rem;     /* 24sp — M3 headlineSmall */
  --fs-dialog-body: 0.875rem;    /* 14sp — M3 bodyMedium / labelLarge */
  --fs-dialog-caption: 0.75rem;  /* 12sp */

  /* Line heights */
  --lh-body: 1.75rem; /* 28 line height for body text */
  --lh-dialog-title: 2rem;      /* 32sp */
  --lh-dialog-body: 1.25rem;    /* 20sp */
  --lh-dialog-caption: 1rem;    /* 16sp */
  /* Myanmar script stacks diacritics above and below the base glyph
     (e.g. အံ့, ဖွယ်), so it needs a taller line box than Latin at the same
     size. Unitless so it tracks the user's font scale. */
  --lh-myanmar: 1.7;

  /* Font scale bounds */
  --font-scale-min: 0.8;
  --font-scale-max: 1.5;
  --font-scale-step: 0.1;

  /* Nav drawer width (320 dp = 320px) */
  --drawer-width: 320px;

  /* Default theme: BLUE */
  --color-primary: ${themes.BLUE.primary};
  --color-bg: ${themes.BLUE.bg};
  --color-card: ${themes.BLUE.card};
}

[data-theme="BLUE"] {
  --color-primary: ${themes.BLUE.primary};
  --color-bg: ${themes.BLUE.bg};
  --color-card: ${themes.BLUE.card};
}
[data-theme="GREEN"] {
  --color-primary: ${themes.GREEN.primary};
  --color-bg: ${themes.GREEN.bg};
  --color-card: ${themes.GREEN.card};
}
[data-theme="PINK"] {
  --color-primary: ${themes.PINK.primary};
  --color-bg: ${themes.PINK.bg};
  --color-card: ${themes.PINK.card};
}
[data-theme="BROWN"] {
  --color-primary: ${themes.BROWN.primary};
  --color-bg: ${themes.BROWN.bg};
  --color-card: ${themes.BROWN.card};
}
`

writeFileSync(out, css, 'utf8')
console.log(`tokens written → ${out}`)
